### ISSUE TITLE
Custom login title

### ISSUE THREAD

**Issue by rokkay** [code16/sharp#131]
Is there any way to customize this string? I checked the code and its hardcoded so when i update Sharp i have to change it.

![Screenshot_2019-04-27-18-00-54-915_org mozilla firefox](https://user-images.githubusercontent.com/47890402/56852074-b649d600-6916-11e9-8216-ed0898acb165.png)

**Comment by dvlpp** [comment]
No, and I'm not sure that we'll need to provide a way you do so... I mean this is the product name, and it only appear on the login page.

**Comment by b0rt** [comment]
Hi, 
building custom backends often requires to hint the user on which system he or she logs in. i would argue that it is a core requirement of any client - project to replace this String with e.g. project name or even upload the logo.. it would be great if there would be a way to theme the login screen.

'sharp' also appears in the page title 'unremovable' (by my investigations). 

Well. I think the adoption of sharp for projects would benefit if those customer facing views could be customized in a 'sharp' way ;)

One 'minimalistic' approach could be to leave 'Sharp' but allow $developer to insert a line below or above (or a logo) to aid its $users

or
<draft> 
$projectTitle
using sharp 4.1.19
</draft>

Would you consider such a PR?

**Comment by dvlpp** [comment]
Yes, I think this makes sense. We already have a `sharp.name` key in the config, used in the top bar menu, maybe we can report this value in some way in the login page? If so, I think it should be larger than "Sharp", to make this understandable, like you proposed.

I also wanted since a long time to allow a logo (PNG? SVG? Both?) instead os just a string. Please feel free to add this feature in your PR, if you choose to write one.
