### ISSUE TITLE
Upload list not working

### ISSUE THREAD

**Issue by Resin01** [code16/sharp#143]
I am trying to add the upload list, but it does not seem to work properly.
I have copied the form code exactly, but when I click "Add a picture" it just adds a new line with a remove button. No upload form is shown,.

![Selection_040 resized](https://user-images.githubusercontent.com/13980140/59840319-6570bf80-9352-11e9-965b-016118a132dd.png)

**Comment by dvlpp** [comment]
Hi,
First idea: have you defined the layout of the list item (related doc: https://sharp.code16.fr/docs/guide/form-fields/list.html#layout)? 

See this example from the Saturn demo project for instance: https://github.com/code16/sharp/blob/97d5f10f0a570214135a17e3ff7d750539b9c748/saturn/app/Sharp/SpaceshipSharpForm.php#L210

**Comment by Resin01** [comment]
Perfect. Didn't realize that was needed. Perhaps you should add this to the "upload" documentation?

**Comment by dvlpp** [comment]
This is needed because a list item could have a complex layout — see this example for a not so complex one, from Saturn again:
![image](https://user-images.githubusercontent.com/973325/59845361-7c68df00-935d-11e9-8d17-8223d0e3104f.png)

This has in fact nothing to do with Uploads: it's related to Lists, and that's why it's located in the List field section of the documentation: https://sharp.code16.fr/docs/guide/form-fields/list.html#layout
