### ISSUE TITLE
Enable SharpFormTagsField to be used without being related to a database table

### ISSUE THREAD

**Issue by nsrosenqvist** [code16/sharp#161]
It'd be great if one could use _SharpFormTagsField_ to not only select from a set of predefined tags that correspond to items in a table but to also simply create a list of strings that is to be stored as data in a single table cell. A perfect example for this would be to create keywords related to a page which is an arbitrary number of items related to the page content and should be presented in a comma separated list in the attribute of an HTML meta tag.

![Screenshot_2019-08-02 SOMA Site, Pages Sharp 4 1 16](https://user-images.githubusercontent.com/1303475/62386392-ffce4080-b557-11e9-9096-a9223c4f93be.png)

This doesn't work currently since `SharpFormTagsField::toFront` expects "an array of id values OR an array of models" which can't be created and matched with the available tags that are populated in `buildFormFields` beforehand, in which one doesn't have access to the instance being edited.

**Comment by dvlpp** [comment]
If I understand correctly, you would like to be able to define a specific tag list for the current instance, rather than a generic one, and since to tag list is defined in `buildFormFields`, you can't do that. If this is your need, I see 2 possible solutions:

First one, use `sharpContext` to build the tag list (https://sharp.code16.fr/docs/guide/context.html):

```php
class MyForm extends SharpForm
{
    use WithSharpFormContext;

    function buildFormFields()
    {
        // We can check that we are in an update case with $this->context()->isUpdate()
        $this->addField(
            SharpFormTagsField::make("tags", User::find($this->context()->instanceId())->getTags())
        );
    }
```

Second solution, more complex and less flexible, use a real dynamic list, and go for an `AutocompleteList` with a remote dataset https://sharp.code16.fr/docs/guide/form-fields/autocomplete-list.html#configuration.

**Comment by nsrosenqvist** [comment]
Correct, context() would enable populating the field with the saved data. Thanks!
