### ISSUE TITLE
Widget that can create/manage hierarchical data

### ISSUE THREAD

**Issue by nsrosenqvist** [code16/sharp#163]
It would be great if a widget for managing hierarchical data was included out of the box. The list field currently supports sorting and it'd be great if that could also support parenting items to each other. Example use cases would be for blog categories or menu editor.

**Comment by dvlpp** [comment]
This isn't in our plans, since it could need complex and different models... For this, I would consider [building a custom form field](https://sharp.code16.fr/docs/guide/custom-form-fields.html#on-the-front-side) (could be very simple because based on a specific model implementation), or handing hierarchy on the EntityList side (with filters).
