### ISSUE TITLE
[Discussion] Problems with integrating the Upload field with third-party media manager

### ISSUE THREAD

**Issue by panda-madness** [code16/sharp#172]
I've spent the last couple of days attempting to make `spatie/laravel-medialibrary` work with Sharp's Upload field. I've encountered a few obstacles. They could be worked around, but the workarounds are a bit hacky, so I've decided to use Sharp's built in uploading feature. However, since spatie's library is pretty popular, I thought it might be useful to document these issues, and maybe open up a discussion on coming up with solutions.

1. `laravel-medialibrary` moves the files that you associate with a model to the disk that it's configured to use. There is no option to use the existing file's path. There is an option to copy the file instead of moving it, but this leads to duplicate files being stored. It's possible to work around this by configuring both Sharp and medialibrary to target the same disk, as well as overriding medialibrary's default folder structure.
2. After transforming an existing image, Sharp returns the array `['transformed' => true]`, modifying the file in-place. However, to sync this change with `medialibrary` I need to find the corresponding `Media` record and update it's file with the transformed one. There is not enough data in the array returned by Sharp to do this.

In my opinion, the current way of working with uploads is a little opinionated towards the built-in uploading functionality. Perhaps it would be better to abstract file uploading behind an interface, provide a base implementation, and let users register custom implementations? Things that would be useful to customize would be uploading, thumbnail generation, image processing.

**Comment by dvlpp** [comment]
I don't have the time, right now, to try a full integration of `spatie/laravel-medialibrary` — I think that's what I should do to fully understand the pain points. My general feeling is that the way Sharp handles uploads, without using `SharpModelUpload`, is as light as it could be (but I could be wrong, I might need to look again since it's a quite old feature)... However, based on what you write, `spatie/laravel-medialibrary` seems very opinionated on disk, folders...

Maybe a stupid idea, but is there a way to extend `spatie/laravel-medialibrary`'s Model, to add some of `SharpModelUpload`'s features there?

**Comment by dvlpp** [comment]
Not a bug; feel free to open a discussion about this
