### ISSUE TITLE
Date range filter on dashboards fail to display retained value

### ISSUE THREAD

**Issue by smknstd** [code16/sharp#189]

**Comment by dvlpp** [comment]
Turns out date is NOT well formed in the retain case:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/973325/68137578-80218a80-ff27-11e9-8349-fd9846e972d6.png">


Should be:

<img width="407" alt="image" src="https://user-images.githubusercontent.com/973325/68137597-8879c580-ff27-11e9-9cad-7e4c21a4f309.png">
