### ISSUE TITLE
Proposal for a global search

### ISSUE THREAD

**Issue by ewatch** [code16/sharp#197]
Hi Philippe,

I was looking a lit bit into improvements of sharp.
Inspired a little bit by Laravel Nova (as it's also compared it) I thought it makes sense to have a global search.

Here are the ideas that I gathered until now:

**Backend**
- Create a global search controller
- loops through all EntityList objects (received with their menu labels from the sharp.config) and checks for the configuration "searchable" being equal to "true"
- fills EntityQueryParamList with searchterm and calls getlist on each EntityList
- uses labels from the config to display results in dropdown

**Frontend**
1. One search field with an option to search globally and locally
1. Adding a second search field which always searches globally (would need some restructuring of the ActionBar)

At a later stage one could think of even showing commands available to entities or entitylists and after that display a modal. It's just an idea for the commands but could make things more effective.

What do you think ?
I could start on working the global search and propose a PR.

**Comment by dvlpp** [comment]
Hi,

Thanks for your proposal. I can see the idea, but I'm wondering if it should really be a new field, in the global UI, or maybe a Widget in a Dashboard? I mean we could rather design a widget with an (kind of) autocomplete field, using a dedicated functional remote endpoint (or even local datastore, in some simple cases) to any entities / resources the user wants, and it could bring some bonuses:
- result templates;
- performance: cycling through a lot of EntityLists, meaning building them, and performing potentially many SQL requests is, I think, not a good idea;
 - plus I'm worried with side effects on using various EntityList's `getListData()` methods;
- and on the potential conflicts with the upcoming big "show view" feature (PR with all the backend code is opened since august: #166).

I think Dashboard widgets are underdeveloped right now, and there is room for this kind of feature here. What do you think?

**Comment by ewatch** [comment]
Hi,

yes I see your point with the amount of SQL requests.
I would propose and agree with you to create that as a widget right now.
Then the "show view" feature can be integrated and after that the topic can be reviewed.

In contrast to Nova with Sharp you provide more freedom to the user of your framework of how to search in the entities whereas in Nova you have define an array of fields.
Through the array it's also easier to optimize for example by creating an index (I don't know if it's done).

I thought about the business being able to just enter a customer number or an order number to jump right to an entity or to type a word and get a filtered entity list.
Still I agree that normal relational databases are not optimized for this and normally at this point search engines come into play.

Thanks for your feedback.
I will create widget prototype soon and then we can talk about it again.

**Comment by dvlpp** [comment]
OK, I'm closing this since it's not an issue. Feel free to use this in the future to continue the discussion, or to open a PR.
