### ISSUE TITLE
4.2 Ui problems with create/update and show

### ISSUE THREAD

**Issue by Insolita** [code16/sharp#210]
Hi! First of all, I glad to see so intensive progress. 
I have tried the new 4.2 tagged version with php7.4 and laravel 6.7

- First, is that create and update forms hangs-up with ajax-preloading after submitting data (Data created/updated successfully and json {"ok": true} returned with 200 status). There are no errors in logs. 

- Second - "Entity show" show nothing (But json returned)
Console show error
![2019-12-16-114126_414x172_scrot](https://user-images.githubusercontent.com/1847402/70877572-fc17f380-1ff8-11ea-960d-61a332b0797f.png)

 as an example of json response

```json
{
"config":[],
"fields":{"slug":{"key":"slug","type":"text","label":"Code"},"title":{"key":"title","type":"text","label":"Title"},"content_raw":{"key":"content_raw","type":"text","label":"Content"}},
"layout":{"sections":[{"title":"Info","columns":[{"size":6,"fields":[[{"key":"title","size":12,"sizeXS":12}]]},{"size":6,"fields":[[{"key":"slug","size":12,"sizeXS":12}]]}]},{"title":"Data","columns":[{"size":6,"fields":[[{"key":"content_raw","size":12,"sizeXS":12}]]}]}]},
"data":{"slug":"xyzasd","title":"\u041f\u0440\u043e\u0432\u0435\u0440\u043a\u0430!!!","content_raw":"**Hello**"},
"breadcrumb":null,
"authorizations":{"view":true,"create":true,"update":true,"delete":true}
}
```

As I see in response, only the breadcrumb value is null. But I don't know how to change it. 

And second is a small mistake in the generated entity.show template 
https://github.com/code16/sharp/blob/master/src/Console/stubs/entity-show.model.stub#L47
ShowLayoutColumn should be used instead of FormColumnLayout

Thanks for attention. Let me know if you need any additional information

**Comment by dvlpp** [comment]
Hi,

Thanks for tour last point, I fixed the stub.

For your first issue, I think the 2 bugs are related: this has to do with the fact that breadcrumb is not set. The front is unable to redirect after update because of that, and the show page needs the breadcrumb to display actions. But I don't understand how it can be null... Here how this works:
- the breadcrumb is stored, in session, on all GET web routes (here for instance: https://github.com/code16/sharp/blob/77059db58474e88a6063c444bd797ab45ec9bdc0/src/routes.php#L140), via the [StoreBreadcrumb](https://github.com/code16/sharp/blob/master/src/Http/Middleware/StoreBreadcrumb.php) middleware.
- and breadcrumb is restored from session and sent with all XHR requests via [AppendBreadcrumb](https://github.com/code16/sharp/blob/master/src/Http/Middleware/Api/AppendBreadcrumb.php) middleware.

I think those middleware are not called in your case... Could you check that? Maybe you have a route caching preventing theses to be called?

**Comment by Insolita** [comment]
Thanks for quick answer. I understand the reason of my problem! 

https://github.com/code16/sharp/blob/master/src/Http/Middleware/StoreBreadcrumb.php#L105
I define own  "custom_url_segment" in config. But StoreBreadcrumb try to find 'sharp'

**Comment by dvlpp** [comment]
Ouch! that's a bug one then. I'll fix this soon. Thanks.

**Comment by dvlpp** [comment]
Was an easy fix, I'll build a version after we fixed some front-related test issues for Travis.

**Comment by dvlpp** [comment]
Done: https://github.com/code16/sharp/releases/tag/v4.2.1.
