### ISSUE TITLE
What about roadmap? 

### ISSUE THREAD

**Issue by Insolita** [code16/sharp#214]
Hi, what about future plans for the platform?
Have you plans to extend default field collection? There are exists the ability to add custom fields, and it is great, but several fields like CodeField (AceEditor or CodeMirror based), RichTextEditor like Quill or TinyMce used really often. And their lack out of the box is very off-putting. 
Also, the bulk image upload feature is in demand

**Comment by dvlpp** [comment]
Hi,

We definitively consider some bulk upload solution, maybe in relation with some list. But as always in this project, we son't want to add something which denatures Sharp bringing some feature with an exception, or a must use pattern. What I mean here is that bulk upload (and bulk command on selected instances, see #164) is in our minds, but we have to figure a good way to implement it (we took some time for the show page for this exact reason).

CodeField do not seems (to me) to be a field that should be in the core... Maybe a custom field?

RichTextEditor is a huge subject. I really (like really) dislike TinyMce-like fields, which handles HTML and result in a lot of crappy data... That's why we preferred a custom Markdown field (with embedded image) and a Trix-based field for wysiwyg. We are also considering, for a future version, a field based on https://tiptap.scrumpy.io, with json-based data.
