### ISSUE TITLE
Question about something like "workflow" or "best practice" ?

### ISSUE THREAD

**Issue by rycks** [code16/sharp#251]
Hello,
i'm working on something on a multi-tab configuration plugin and i would like to add a button to test if settings are good, something like that for example:

<img width="859" alt="image" src="https://user-images.githubusercontent.com/1468823/84478870-4c170080-ac92-11ea-811d-98730a256126.png">

what could be the best solution in "code/sharp" point of view ? add a custom object "button" ? or something else ?

this is important because of the others tabs ("dolibarr" part of form will come from a external request on URI and APIKEY from the first tab) ...

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1468823/84479020-87b1ca80-ac92-11ea-8070-f8429eb92127.png">

So what is your point of view about that ? some ideas or suggestions ?

Thanks

**Comment by dvlpp** [comment]
Well, for this I think the best way is a show page with a custom show field: they are available on Sharp 5.0, which is close to a proper release and pretty stable right now (we are using it at Code 16 on production projects). Show page are available in 4.2 and [documented here](https://sharp.code16.fr/docs/guide/building-entity-show.html), and [this is the link for documentation of custom show field](https://github.com/code16/sharp/blob/next/docs/guide/custom-show-fields.md) in 5.0.

We have something similar in one of our projects (it's a Show page):
<img width="617" alt="image" src="https://user-images.githubusercontent.com/973325/84511283-987c3380-acc6-11ea-9612-bdc09bc8498b.png">

I would go for this because a test like this won't really work on a form, where URL and API key can change.

Another solution could be to write a command for this, and to call it from the entity list (4.2 compatible + no custom field at all).
