### ISSUE TITLE
Using sharp_auth middleware for autocomplete always results in 401

### ISSUE THREAD

**Issue by stickgrinder** [code16/sharp#260]
Following the guide for Autocomplete fields I configured and endpoint route like this:

```php
// routes/api.php
Route::get('/meta/origins', 'MetaOriginsController@index')->middleware('sharp_auth');
```
but I can't get it to work. I'm not exactly expert of Laravel authentication layer. I tried tinkering with the sharp configuration but with no result.

I spied over Saturn code and I saw the spaceship endpoints are implemented as normal web controllers with no protection.
I guess I'm missing something stupid. Any clue?

Thanks

**Comment by dvlpp** [comment]
Mmm, I think you are using the regular Laravel `api` middleware group, putting these endpoints in `routes/api.php`, which is missing by default all `session` related stuff (https://github.com/laravel/laravel/blob/fa43c0a333d623a393fa33c27a1376f69ef3f301/app/Http/Kernel.php#L42). Laravel is assuming you are using some stateless auth, token-based for instance.

Since Sharp is using by default a regular session based auth, you'll have to move these routes to web.php.

**Comment by stickgrinder** [comment]
Thanks for your reply @dvlpp.

I actually tried to specify using the session group for authentication even in the API routes but it didn't work. I'll try doing what you said; if it works, it's at least a nudge in the right direction to understand what's happening under the hood.

Keeping you posted. Thanks

**Comment by dvlpp** [comment]
Closed (inactivity)
