### ISSUE TITLE
LangController doesn’t use the locale parameter

### ISSUE THREAD

**Issue by mlajx** [code16/sharp#274]
# `LangController` doesn’t use the `locale` parameter

First of all, I apologize for my english, this is not my native language.

In my search for how I could 'force' the language definition for sharp, I realized that it always carries the url "/vendor/sharp/lang.js?version=5.2.0&locale={{lang}}", in where {{lang}} is the current language configured in laravel.

But I noticed in the `LangController` file, that it doesn’t get this locale parameter:

```PHP
//...

$lang = app()->getLocale();

//...
```

I want to send a PR with the following solution

```PHP
use Illuminate\Http\Request;


public function index(Request $request)
{
        $lang = $request->input('locale') ?? app()->getLocale();

        //...
}

```

But I would like to know before I do the PR if there is any kind of problem, conflict or vulnerability that can happen.

**Comment by kravetz** [comment]
I believe it happens because sharp is not using ISO 639-1 (pt) + ISO3166-1 (BR), according to RFC5646 (https://www.rfc-editor.org/rfc/rfc5646), but Laravel uses it by default.

So instead of pt-br, the folder in resources/lang/ should be pt-BR, then it will work. Also, ko-kr should be renamed to ko-KR
