### ISSUE TITLE
Need example for integrate custom controllers and views

### ISSUE THREAD

**Issue by Insolita** [code16/sharp#28]
You make excellent job, and your api covered many use-cases, but sometimes more complex logic is neccessary. For example i have api-controller and vue-components based on vue-simple-calendar for adding events,  custom quiz-constructor, and  now i looking for way to inject it in the sharp layout

**Comment by dvlpp** [comment]
For now, custom fields are not possible. This is a planned feature, but we must approach this carefully because communication between front components and back code is a bit complex and could really easily cause bugs in the project functional code. All of our projects at Code 16 which use Sharp (which means most of them) are only depending on the default form fields.
