### ISSUE TITLE
Contribution to the documentation

### ISSUE THREAD

**Issue by IlyasDiker** [code16/sharp#309]
**[enhancement]**
We would love to contribute to the documentation. Is it going to be possible?
or a Discord community so we can help each others

**Comment by dvlpp** [comment]
First, of course you can submit PR to enhance the doc. Here's how: all the markdown files are on `/docs/guide`, and since we are using VuePress for the documentation, to build it locally you should run `npm install && npm run dev` on the `/docs` folder.

For the Discord, it's a good idea, and we already thought about it. Let me check where we are on this with @aguingand and we'll come back to you in this issue.

**Comment by dvlpp** [comment]
OK, I created a Discord server: https://discord.gg/kmVAwGUt (thanks for the boost on that). We will add it in the header of the Sharp documentation site (sharp.code16.fr), but in the meantime everybody reading this can join (it's very empty for now).

**Comment by IlyasDiker** [comment]
Thanks. 👌
