### ISSUE TITLE
EntityList - parent info

### ISSUE THREAD

**Issue by anigroSIS** [code16/sharp#323]
Is there a way to add a section with any parent information for children EntityList?
Before the EntityList, as the filters in action_bar, I need to show a info_bar with any parent info. 
I want avoid to show the same info foreach row.

**Comment by dvlpp** [comment]
I don't understand quite your question, but it seems to be a request for help rather than a bug report... Could you please use Discord (https://discord.com/invite/sFBT5c3XZz) for that, as it is becoming our chosen platform for support / help? I'm closing this, but please ask for help there (maybe with more details and/or a screenshot).
