### ISSUE TITLE
[Feature Request] Support forCustom Pages

### ISSUE THREAD

**Issue by uwascan** [code16/sharp#367]
Hi @dvlpp, Is it possible for sharp to provide support for Custom Pages that can be linked to in the menu giving developers the freedom to use custom components as described in [Issue #250](https://github.com/code16/sharp/issues/250). I dont think using a custom show field is suitable for my usecase. using a custom show field implies you are tied to using an entity. I would gladly use a custom show field if there is a way to make it stand alone. I am looking at creating a custom PDF report viewer page and a special invoice creation Page and some other complex pages that goes beyond just Lists and forms (I am using shart as an application framework not a CMS backend). Any Guidance or tips on how to do this with current sharp feature will be appreciated. Thanks.

**Comment by dvlpp** [comment]
Hi,

I don't have any advice for this type of usage of Sharp, sadly: I mean, Sharp allows to do many things, with show pages and forms and commands, but as I see it the project needs to have clear, manageable and understood boundaries. 

We use Sharp a lot, in our company, for e-commerce or transaction applications, and we manage invoices, including generation, with lists and commands with forms. Anything beyond that may require a dedicated app — note that since Sharp is a package, you can technically make it work alongside another tool (with maybe a link in the menu, or in a show page).

Anyway we do not intend to allow more customization, once again in order to keep Sharp manageable.

**Comment by uwascan** [comment]
@dvlpp Thanks for sharing your thoughts and it is understandable.
