### ISSUE TITLE
Display bug when I create two SharpShowEntityListField column

### ISSUE THREAD

**Issue by hichxm** [code16/sharp#384]
I have this following front bug when I use two SharpShowEntityListField :

![bug](https://i.postimg.cc/7LzgcNDP/2022-01-27-03-01.png)

To fix it, I need to set collapsable as true.

```php
    // App\Sharp\Shows\UserEntityShow 

    protected function buildShowLayout(ShowLayout $showLayout): void
    {
        $showLayout
            ->addSection('', function(ShowLayoutSection $section) { 
                $section
                    ->setCollapsable() // set as false to do the bug
                    ->addColumn(6, function(ShowLayoutColumn $showLayoutColumn){
                        $showLayoutColumn->withSingleField('roles');
                    })
                    ->addColumn(6, function(ShowLayoutColumn $showLayoutColumn){
                        $showLayoutColumn->withSingleField('servers');
                    });
            });
    }
```

Now, is work
![work](https://i.postimg.cc/Fs1k8xVt/2022-01-27-03-05.png)

**Comment by dvlpp** [comment]
Mmm, the thing is EmbeddedEntityLists are meant to be in their own sections in the layout, via `$showLayout->addEntityListSection('XXX')`  (see https://sharp.code16.fr/docs/guide/building-show-page.html#buildshowlayout-showlayout-showlayout-void) — this is because there are many specificities here: create button, filters, search... 

TBH I think the bug here is that we should throw an exception saying that `roles` and `servers` are not eligible as single fields (if I understood your case).

**Comment by dvlpp** [comment]
Closing this (inactivity)
