### ISSUE TITLE
Validator vs Formatter

### ISSUE THREAD

**Issue by irman** [code16/sharp#57]
Hi,

From what I found out, when we're using a Validator, it's triggered _before_ it hits `SomeFormatter::fromFront()`. Is this intended? It has occurred to me that this causes problem when trying to validate existence (using Laravel's Exists rule) in an autocomplete field. It appears that the the data that the Validator's got are in array instead of in `id` like it's supposed to (post formatted).

I managed to overcome the issue but it's quite hacky and not really elegant. Is there a better solution?

Thanks!

**Comment by dvlpp** [comment]
Yes, you are right, validator is executed before formatter, and I think this was because of some complexities with delayed data and eloquent ([see here](https://github.com/code16/sharp/blob/34f1079e705906942f7ce171a7c4e5583b6e2d2b/src/Form/SharpForm.php#L156)).

Since we already have a special validation case for Wysiwyg fields, [documented here](https://github.com/code16/sharp/blob/master/docs/building-entity-form.md#validate-rich-text-fields-markdown-and-wysiwyg), I think autocomplete field validation should also be handled by `\Code16\Sharp\Form\Validator\SharpFormRequest` class. I may look for this in the future, but in the meantime if you want to go from there and make a PR, please do!
