### ISSUE TITLE
Authorizations for instance command make lot of queries

### ISSUE THREAD

**Issue by Insolita** [code16/sharp#68]
https://github.com/code16/sharp/blob/master/docs/commands.md

```php
public function authorizeFor($instanceId): bool
    {
        return Spaceship::findOrFail($instanceId)->owner_id == sharp_user()->id;
    }
```
make query for each instance in list; (if we show list with 50 items per page, it calls 50 queries)

If we have got access to instance directly, instead of instanse id, queries will be decreased.

```php
public function authorizeFor($instance): bool
    {
        return $instance->owner_id == sharp_user()->id;
        // Even  return $instance->parent->owner->id == sharp_user()->id;
        // if we build query with('parent')  for entity list
    }
```

also that bring ability to show filter conditionaly, for example  return $instance->state == 'ready';

**Comment by dvlpp** [comment]
Yeah, I'm aware of that, but I'm afraid there is no good solution to this. Authorizations are added after data transformation, and at this stage there are no models, but only arrays of attributes. And beside, Sharp is not able to find out how to grab an instance, given it is data agnostic (We don't rely on Eloquent).
We could pass an array of attributes instead of a single id, and we've done that at a point, but this was worse: attributes depends of entity list columns (which can change over time), and authorizations can be checked without relation to an entity list at execution (https://github.com/code16/sharp/blob/34f1079e705906942f7ce171a7c4e5583b6e2d2b/src/Http/Api/Commands/InstanceCommandController.php#L68).
The best solution for Sharp seems to be this one: let each Command to be responsible for this. It's a performance loss, but it's the price to pay for flexibility...
