### ISSUE TITLE
Needs better navigation solution

### ISSUE THREAD

**Issue by Insolita** [code16/sharp#72]
For example we have the Post entity;
Post hasMany  comments
Post has Many user rates

We can create CommentEntityList and PostRate entityList with default filter by post_id and show post-related lists. we don't show this lists in menu, because its not independent.  And there is only one way to create links between Posts and related staff - it is  create actions like "show post comments", "show user rates"  for post, and "go to post" for sub-entities.  And it is not comfortable solution, because in action menu mixed view/navigation links and true action commands. Action list can be very large for rich entities like an user, post, product. Also we hasn't opportunity for breadcrumbs building

Other case - that is for some entities only one list is not enough. Some times we need to show lists with different grouped items, or with different columns

**Comment by dvlpp** [comment]
I'm not sure I fully understand the problem, but maybe a possible solution for the Post - Comments thing is to have 2 lists and add links directly in each row. [See an example here](https://github.com/code16/sharp/blob/2f1a98e50f804a821dbbd943f7cdc2eb06762d6d/saturn/app/Sharp/SpaceshipSharpList.php#L122): 

```php
 ->setCustomTransformer("pilots", function($pilots, $spaceship) {
    return $spaceship->pilots->map(function($pilot) {
        return (new LinkToEntity($pilot->name, "pilot"))
            ->setTooltip("See related pilot")
            ->setSearch($pilot->name)
            ->render();
        })->implode("<br>");
```

<img width="950" alt="image" src="https://user-images.githubusercontent.com/973325/51071642-b4ecea00-1654-11e9-9386-0b0196fc3a41.png">

(Of course, you can set a filter instead of a search, in the link, or even link to a form).

Is this a solution for your situation?

Another idea: you can quite easily handle a Comments list in the Post entity (with a List form field, I mean) AND also propose a full Comment entity with a Post link via an autocomplete field. Having the relation on both side is not a problem, and could be easier for the user.

**Comment by Insolita** [comment]
List form field is good for a little related data such as tags, related categories, but if related data is over than thousand records, it not useful without own search/filtration

LinkToEntity is good decision, It not described in documentation

**Comment by dvlpp** [comment]
Autocompletes, as form field, can be configured as ‘remote’ (see doc), with full control on custom search.

**Comment by irman** [comment]
I think the author (@dvlpp ) means something like this (note on the filters): 

![image](https://user-images.githubusercontent.com/6107943/51155486-9f74fb80-18b2-11e9-8e36-e493a4b172df.png)

![image](https://user-images.githubusercontent.com/6107943/51155515-b4518f00-18b2-11e9-9c93-108e0a402a29.png)


Just wondering, do you have any plans on having a "show" view? Thus doing something like what the OP wanted may be possible?

**Comment by dvlpp** [comment]
@irman yes, but instead of a command to list models, I'd use LinkToEntity (see the 2nd comment of this issue): a simple link on the models count.

On the "show" view: we do think about it, we just needed to find the correct way to handle it.

**Comment by dvlpp** [comment]
Closing this since it's not an actual issue report.
